# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, mtl, parsec, picosat }:

cabal.mkDerivation (self: {
  pname = "picologic";
  version = "0.1";
  sha256 = "05fc33fcfe311c1db655a6376a02eb1975954d6c8c17634a8e727c20149b5dd9";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ mtl parsec picosat ];
  meta = {
    homepage = "https://github.com/sdiehl/picologic";
    description = "Utilities for symbolic predicate logic expressions";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
