# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, mtl, parsec, picosat }:

cabal.mkDerivation (self: {
  pname = "picologic";
  version = "0.1";
  sha256 = "40b8f3a30f200f956d967c4bfa8063cbaf9a9e1963c246cffcc79e8e5da29193";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ mtl parsec picosat ];
  meta = {
    homepage = "https://github.com/sdiehl/picologic";
    description = "Utilities for symbolic predicate logic expressions";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
